// Generated from the launcher's ui/components/RewardIcons.kt - change the two together.
// The daily rewards' and pass's prizes as 16x16 pixel icons: our own art, one sprite per kind of prize.

export const REWARD_PALETTE: Record<string, string> = {
  "k": "#24160E",
  "r": "#A52A12",
  "o": "#E8631C",
  "y": "#FDBA2C",
  "l": "#FFE36E",
  "w": "#FFF8E4",
  "G": "#F2C230",
  "D": "#B27812",
  "b": "#6B3F1E",
  "B": "#A0682F",
  "T": "#D9C49A",
  "g": "#3F4048",
  "s": "#7C7E88",
  "S": "#BEC0C8",
  "c": "#4FC3DA",
  "C": "#B6F1FF",
};

export const SPRITES: Record<string, string[]> = {
  CHEST: [
    "................",
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kBBBBBBBBBBBBk.",
    ".kBbbbbbbbbbbBk.",
    ".kkkkkkGGkkkkkk.",
    ".kbbbbkGGkbbbbk.",
    ".kBBBBBkkBBBBBk.",
    ".kBBBBBBBBBBBBk.",
    ".kbbbbbbbbbbbbk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
  ],
  HALO: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "....kkkkkkkk....",
    "..kkGGGGGGGGkk..",
    ".kGGllkkkkllGGk.",
    ".kGDk......kDGk.",
    ".kDDDkkkkkkDDDk.",
    "..kkDDDDDDDDkk..",
    "....kkkkkkkk....",
    "................",
    "................",
    "................",
    "................",
  ],
  CROWN: [
    "................",
    "................",
    "................",
    ".k.....kk.....k.",
    "kyk...kyyk...kyk",
    "kGGk.kGyyGk.kGGk",
    "kGGGkGGGGGGkGGGk",
    "kGGGGGGGGGGGGGGk",
    "kGrGGGoGGoGGGrGk",
    "kGGGGGGGGGGGGGGk",
    "kDDDDDDDDDDDDDDk",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
    "................",
    "................",
  ],
  PICKAXE: [
    "................",
    "...kkkkkkkkkk...",
    ".kkoyyyyyyyyokk.",
    "koorrrrrrrrrrook",
    "kok...kBbk...kok",
    "kk....kBbk....kk",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kBbk......",
    "......kkkk......",
    "................",
  ],
  NAMETAG: [
    "................",
    "................",
    "................",
    "................",
    "...kkkkkkkkkkkk.",
    "..kTTTTTTTTTTTTk",
    ".kTTwwwwwwwwTTTk",
    "kTkTTTTTTTTTTTTk",
    ".kTTwwwwwwTTTTTk",
    "..kTTTTTTTTTTTTk",
    "...kkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  BOOTS: [
    "................",
    "................",
    "................",
    "..kkkk....kkkk..",
    "..kbbk....kbbk..",
    "..kbbk....kbbk..",
    "..kbbk....kbbk..",
    "..kobk....kobk..",
    "..kbbkk...kbbkk.",
    "..kbbbbk..kbbbbk",
    "..kbbbbk..kbbbbk",
    "..kkkkkk..kkkkkk",
    "................",
    "................",
    "................",
    "................",
  ],
  LANTERN: [
    "................",
    ".......kk.......",
    "......k..k......",
    ".....kkkkkk.....",
    ".....kggggk.....",
    "....kkkkkkkk....",
    "....kgcCCcgk....",
    "....kcCwwCck....",
    "....kcCwwCck....",
    "....kgcCCcgk....",
    "....kkkkkkkk....",
    ".....kggggk.....",
    ".....kkkkkk.....",
    "................",
    "................",
    "................",
  ],
  CLOAK: [
    "................",
    "...kkkkkkkkkk...",
    "...korrrrrrok...",
    "...korrrrrrok...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "...krrroorrrk...",
    "...kroooooork...",
    "...krrroorrrk...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "...kkkkkkkkkk...",
    "................",
    "................",
  ],
  TRAIL: [
    "..............w.",
    ".............wlw",
    "..............w.",
    "...........ly...",
    "..........yo....",
    ".........yo.....",
    "....w...or......",
    "...wlw.or.......",
    "....w.or........",
    ".....or.........",
    "....or..........",
    "...r............",
    "..r......l......",
    "........lyl.....",
    ".........l......",
    "................",
  ],
  PARTICLES: [
    "................",
    "..kk............",
    ".kssk......kk...",
    ".kSsk.....kssk..",
    "..kk......kSsk..",
    "...........kk...",
    "......kkk.......",
    ".....ksSsk......",
    ".....kssgk......",
    "......kkk.......",
    ".kk..........k..",
    "kgsk........ksk.",
    ".kk..........k..",
    "........kk......",
    ".......ksgk.....",
    "........kk......",
  ],
  EMOTE: [
    "................",
    "..kkkkkkkkkkkk..",
    ".kwwwwwwwwwwwwk.",
    ".kwwwwwoowwwwwk.",
    ".kwwwwwoowwwwwk.",
    ".kwwwwwoowwwwwk.",
    ".kwwwwwoowwwwwk.",
    ".kwwwwwwwwwwwwk.",
    ".kwwwwwoowwwwwk.",
    ".kwwwwwwwwwwwwk.",
    "..kkkkwwkkkkkk..",
    "......kwk.......",
    ".......kk.......",
    "................",
    "................",
    "................",
  ],
  PET: [
    "................",
    "................",
    "..kk........kk..",
    ".kbbk......kbbk.",
    ".kbBBkkkkkkBBbk.",
    "..kBBBBBBBBBBk..",
    "..kBBkBBBBkBBk..",
    "..kBBBBBBBBBBk..",
    "..kBBBwwwwBBBk..",
    "...kBwwkkwwBk...",
    "....kwwwwwwk....",
    ".....kkkkkk.....",
    "................",
    "................",
    "................",
    "................",
  ],
  BANNER: [
    "..kkkkkkkkkkkk..",
    "..kbbbbbbbbbbk..",
    "..kkkkkkkkkkkk..",
    "...kssssssssk...",
    "...kssssssssk...",
    "...ksssoosssk...",
    "...ksoooooosk...",
    "...ksssoosssk...",
    "...ksssrrsssk...",
    "...kssssssssk...",
    "...kssssssssk...",
    "...kssk..kssk...",
    "...kkk....kkk...",
    "................",
    "................",
    "................",
  ],
  AURA: [
    "................",
    ".......r........",
    "......ror.......",
    "......rorr......",
    ".....rooor......",
    "..r..royyor..r..",
    "..rr.royyyor.rr.",
    "...rorroyllyorr.",
    "...roooylwlyoor.",
    "...royylwwwlyor.",
    "....royllwllyor.",
    "....rooyllllyor.",
    ".....rooyyyyor..",
    "......rrooorr...",
    "........rrr.....",
    "................",
  ],
  OPEN_PRESENT: [
    "......kGkGk.....",
    "..kkkkkkkkkkkk..",
    "..krrrrGGrrrrk..",
    "..kkkkkkkkkkkk..",
    "......l..l......",
    "....l..ly..l....",
    ".kkkkkkkkkkkkkk.",
    ".kyyyyyywwyyyyk.",
    ".kkkkkkGGkkkkkk.",
    "..krrrrGGrrrrk..",
    "..krrrrGGrrrrk..",
    "..kGGGGGGGGGGk..",
    "..krrrrGGrrrrk..",
    "..kDrrrGGrrrDk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  HAT: [
    "................",
    "................",
    "................",
    "................",
    ".....kkkkkk.....",
    ".....kbbbBk.....",
    ".....kbbbBk.....",
    ".....kbbbBk.....",
    ".....koooyk.....",
    ".....kbbbBk.....",
    "..kkkkkkkkkkkk..",
    ".kbbbbbbbbbbBBk.",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
    "................",
  ],
  GAUNTLET: [
    "................",
    "....kkkkkkk.....",
    "....kSsSsSk.....",
    "....kSsSsSk.....",
    "..kkksssssk.....",
    "..kSkSSSSSk.....",
    "..kSsssssskk....",
    "...kkssssssk....",
    "....ksssssk.....",
    "....kooooyk.....",
    "...kgggggggk....",
    "...kgsgsgsgk....",
    "...kgggggggk....",
    "...kkkkkkkkk....",
    "................",
    "................",
  ],
};

/** The icon for a prize, by the words in its name (RewardIcons.kt `rewardSprite`). */
export function spriteFor(name: string): string[] {
  const n = name.toLowerCase();
  if (n.includes("legend")) return SPRITES.OPEN_PRESENT;
  if (n.includes("halo")) return SPRITES.HALO;
  if (n.includes("gauntlet")) return SPRITES.GAUNTLET;
  if (n.includes("hat")) return SPRITES.HAT;
  if (n.includes("crown")) return SPRITES.CROWN;
  if (n.includes("pickaxe")) return SPRITES.PICKAXE;
  if (n.includes("name tag")) return SPRITES.NAMETAG;
  if (n.includes("boots")) return SPRITES.BOOTS;
  if (n.includes("lantern") || n.includes("charm")) return SPRITES.LANTERN;
  if (n.includes("companion") || n.includes("pup")) return SPRITES.PET;
  if (n.includes("emote")) return SPRITES.EMOTE;
  if (n.includes("particle")) return SPRITES.PARTICLES;
  if (n.includes("trail")) return SPRITES.TRAIL;
  if (n.includes("banner")) return SPRITES.BANNER;
  if (n.includes("cloak") || n.includes("cape")) return SPRITES.CLOAK;
  if (n.includes("aura")) return SPRITES.AURA;
  return SPRITES.CHEST;
}
